name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - feature-frontend
      - feature-backend
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
     # Plataformas de trabajo

    services:
      postgres:
        image: postgres:13  # Versión de PostgreSQL que prefieras
        options: --health-cmd="pg_isready -U postgres" --health-timeout=5s --health-interval=10s --health-retries=5
        ports:
          - 5432:5432  # Expone el puerto de PostgreSQL
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: 1459
          POSTGRES_DB: taller_db

    steps:
      # Obtener el código
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Configurar Node.js (versión que uses)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Instalar las dependencias
      - name: Install dependencies
        run: npm install

       # Ejecutar los tests
      - name: Run tests
        run: npm test
